### ISSUE TITLE
`file` schema not supported

### ISSUE THREAD

**Issue by noel-yap** [protop-io/protop#28]
```
$ cat protop.json
{
  "organization" : "noelyap",
  "name" : "setter-for-catan-tsx",
  "version" : "0.1.0",
  "include" : [ "." ],
  "private": true,  
  "dependencies" : {
    "noelyap/setter-for-catan": "git:file:///home/nyap/tasks/setter-for-catan/setter-for-catan-protos"
  }
}
$ protop sync
Syncing external dependencies.
Could not find package noelyap/setter-for-catan file:///home/nyap/tasks/setter-for-catan/setter-for-catan-protos.
```

**Comment by jefferyshivers** [comment]
This sounds like a nice feature request! Currently dependencies with `git:`-prefixed paths are only supported with web URLs.

For now, you can run `protop link` in the source for your `noelyap/setter-for-catan` project, and that will link your project on the file system (just like `yarn link`). You can then run `protop sync -l` to sync dependencies while including linked projects (`-l` is synonymous with `--use-links`).

**Comment by noel-yap** [comment]
I had started implementing this feature but it looks like it's already implemented (but not yet released).
